### PR TITLE
Encode qcstatements according to latest spec

### PR DESCRIPTION
**Pull request by bouk**
Resolves https://github.com/creditkudos/eidas/issues/24

cc @FaizRasool

### CODE REVIEW

**Review by hatstand — COMMENTED** [review]
Open Banking Directory seems to parse CSRs with this change just fine and generate a certificate but I can't test this for true eIDAS certs.

Do you mind squashing the commits?

**Comment by bouk** [comment]
done

**Review by hatstand — APPROVED** [review]

**Comment by hatstand** [comment]
@bouk We require signed commits for this repo - is it easy for you to sign your commit? If not, I can probably sign yours and commit it.

**Comment by bouk** [comment]
I don't have signing set up

**Comment by hatstand** [comment]
Recreated here: https://github.com/creditkudos/eidas/pull/26

**Pull request closed without merging**
